---
- block:

  - name: Create docker registry directory
    file:
      path: /srv/docker-registry
      mode: 0755
      group: root
      owner: root
      state: directory

  - name: Template docker registry configuration
    template:
      src: config.yml.j2
      dest: /srv/docker-registry/config.yml
      mode: 0644
      owner: root
      group: root

  - name: Start docker registry
    command: >
      docker run -d --name registry -p 5000:5000
      -v /srv/docker-registry/config.yml:/etc/docker/registry/config.yml
      --restart=always registry:2
