---
- hosts: tag_Role_consul_server
  gather_facts: yes
  tasks:
  - name: Gather hostvars for cluster managers
    ec2_facts:

- hosts: tag_Name_management
  gather_facts: yes
  roles:
  - consul-agent
  - nomad-agent
