---
- name: Gather ec2 facts
  ec2_facts:

- block:

  - name: Add Nomad server configuration file
    template:
      src: server.hcl.j2
      dest: /etc/nomad.d/server.hcl
      mode: 0644
      owner: root
      group: root
    notify:
    - reload nomad

  - name: Enable Nomad service
    service:
      name: nomad
      enabled: yes
      state: started
  
  become: yes
